### ISSUE TITLE
Ignore duplicates

### ISSUE THREAD

**Issue by arjanfrans** [mjaneczek/auto-import-preloader#1]
If an import with the same name is already manually imported I get a duplicate declaration error.

I'd like this module to ignore the auto-import if it is already there.

**Comment by mjaneczek** [comment]
It's cool idea!

I am gonna to add this tomorrow and let you know.

**Comment by mjaneczek** [comment]
Hello!

I added the 'skip if defined' functionality! https://github.com/mjaneczek/auto-import-preloader/commit/053b3e457ab4d44efb59cd820e12e0146401a5f2

Remember that it's very simple library and it just searches for text in your files (so your build will be slower).
